name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check file structure
        run: |
          echo "Current workspace: ${{ github.workspace }}"
          ls -R ${{ github.workspace }}

      - name: Detect package manager
        id: detect-package-manager
        run: |
          echo "Current workspace: ${{ github.workspace }}"
          if [ -f "${{ github.workspace }}/my-app/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: my-app/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            my-app/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('my-app/package-lock.json', 'my-app/yarn.lock') }}-${{ hashFiles('my-app/**.[jt]s', 'my-app/**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('my-app/package-lock.json', 'my-app/yarn.lock') }}-

      - name: Install dependencies
        run: |
          echo "Running package manager: ${{ steps.detect-package-manager.outputs.manager }}"
          ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
        working-directory: my-app

      - name: Build with Next.js
        run: |
          echo "Running build with: ${{ steps.detect-package-manager.outputs.runner }}"
          ${{ steps.detect-package-manager.outputs.runner }} next build
        working-directory: my-app

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: my-app/out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
